### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by jonasstein** [bluescan/tacent#1]
Hi, Tristan, 
sorry for misusing this bug tracker, but I could not find your mail contact.
We distribute your proggy fonts on Gentoo Linux (https://bugs.gentoo.org/571998). It would help distributions a lot, if you would provide the fonts in a bundle with a semantic version. http://semver.org/
You could put them for example into your github repository, select MIT license and tag a release with a version. Others can improve the fonts then easier and distributors see, if there was an update.
Thank you very much for your fonts. Jonas

**Comment by bluescan** [comment]
Hi Jonas, Well, better late than never. There is now a repo called [proggyfonts](https://github.com/bluescan/proggyfonts) and an initial release.
