### ISSUE TITLE
Sorry for writing here.

### ISSUE THREAD

**Issue by learningtime2025** [bluescan/tacent#13]
Hello. Sorry for writing here, but i felt sad about Tactile 3D.
I lost my backup drive and have no backup of it. Not the thing i'm using everyday, but sometime its helping a much. 
Can i hope for some binaries and themes?

**Comment by bluescan** [comment]
Hi learningtime. I'll see if I can find the installer in the next week or so... cool that it still runs ;)

**Comment by learningtime2025** [comment]
### **Thank you very much!**
its always sad to lose some data (raid 5 bit rot), but its more sad when there is some rare old things in it, that is not available in the internet anymore.
That software is a part of the "good old times".
about the way, some SW developers make something like that: http://www.x-setup.net/
but seems like domain is gone :(

**Comment by bluescan** [comment]
[TactileV1.4.0.3310.zip](https://github.com/bluescan/tacent/files/14082655/TactileV1.4.0.3310.zip)

See attached. If you can get me your e-mail I may be able to generate a key... or if you already have a key it should work.

**Comment by learningtime2025** [comment]
I'm not sure is it spam-safe to post email here. here is a middle one learningtime2025@gmail.com
can we continue conversation there?

**Comment by bluescan** [comment]
[e-mail deleted for privacy]
