### ISSUE TITLE
Feature request: A transparency-aware viewer that ... actually uses transparency. (?)

### ISSUE THREAD

**Issue by ScientificMethodist** [bluescan/tacent#2]
Hello,
First let me thank you for writing a truly professional and is quite efficient.  I am getting load times that are impressive, and think the thumbnail view and tiling will be great for game devs.  I was pretty surprised that you don't actually implement transparency with the actual background , as far as I can tell.   Hopefully I'm using the right words.. I mean generally the wallpaper and icons that the user has, or an explorer window, possibly a mp4 player, etc. 

Do you know of a viewer that actually allows for this?  I am embarrassed to say I can't find one that works at all.  The most promising project/viewer said my hardware was insufficient to properly build an overlay- but in my mind hardware shouldn't be an issue.  Software rendering of transparent sprites has been used in video games since the 90s.  On silly cam sites there is virtual stripper who runs around your browser using "punch-through" 1-bit transparency that animated GIFs support.. that is essentially the sort of functionality I seek.  Even a chroma-key (green screening) would be better than nothing; although I would prefer .APNG or .GIF support. 

Thanks for taking the time to read my request.  If it is out of the scope of your project I apologize.  

Best,
The Razor (Noah)

**Comment by bluescan** [comment]
Thanks for the kind words regarding thumbnail loading times. The most that could be done in the viewer itself is to support a user-specified background image, assuming the  current checkerboard or solid colour is not sufficient. It doesn't quite sound like this is what you're after though.

**Comment by bluescan** [comment]
This issue was in wrong project (should be in TacentView). It has been added.
TacentView commit
f07fa97f
f07fa97f3e4e63cbcc285473f22d2bf32e68ab41
Option to set transparent work area. Allows images (including animated ones with transparency like webp) to be displayed over whatever is behind the application window, like your desktop or other windows.

**Comment by bluescan** [comment]
1.0.16 supports apng.
